### PR TITLE
Filter by availability function

### PR DESCRIPTION
**Pull request by YowSiaoKang**

### CODE REVIEW

**Comment by YowSiaoKang** [comment]
changes:
1. change availabilities to only accept dates in dd/MM/yyyy formats
2. availability value now supports optional / multiple values
3. updated the find function to parse additional attribute prefix for the search eg.
- find by name: "find n/ alice bob charlie"
- find by availability: "find a/ 01/01/2024 12/12/2024"
- find by name and availability: "find n/ alice a/ 01/01/2024 12/12/2024"

**Comment by YowSiaoKang** [comment]
changes:
1. change availabilities to only accept dates in dd/MM/yyyy formats
2. availability value now supports optional / multiple values
3. updated the find function to parse additional attribute prefix for the search eg.
- Example(find by name): "find n/ alice bob charlie"
- Example(find by availability): " + COMMAND_WORD + " " + PREFIX_AVAIL + " 01/01/2024 12/12/2024\n"
- Example(find by name and availability): " + COMMAND_WORD + " "
            + PREFIX_NAME + " alice " + PREFIX_AVAIL + " 01/01/2024 12/12/2024"

**Review by tayziyi — APPROVED** [review]
Functionality tested, looks good!

**Review by xuwen-ho — COMMENTED** [review]
Stated functionality works with regards to 1) availability fixed format and 2) find command

**Review by xuwen-ho — APPROVED** [review]

**Pull request merged**
